### ISSUE TITLE
Ref in AvailabilityZones throws not an array error.

### ISSUE THREAD

**Issue by paalvibe** [arminhammer/wolkenkratzer#2]
When I use a Ref in AvailabilityZones like
`
{
    "Parameters": {
        "FooAvailabilityZones": {
            "Type": "List<AWS::EC2::AvailabilityZone::Name>",
            "Description": "List of AZ to deploy station in, example: 'eu-west-1a,eu-west-1b' "
        },
...
    },
    "Resources": {
        "ScalingGroupFoo": {
            "Type" : "AWS::AutoScaling::AutoScalingGroup",
            "Properties": {
...
                "AvailabilityZones": {
                    "Ref": "Station<segmentId|pascal>AvailabilityZones"
                },
...
}
`

When I run Template().import(json) in this I get `SyntaxError: AvailabilityZones must be an array in AutoScalingGroup`. How can I fix that or work around it or am I doing something wrong?

**Comment by arminhammer** [comment]
Hi @paalvibe, thanks for reporting the issue! The import function should work for all templates, but it has not had a lot of testing so far. I intend to add more robust testing before releasing 1.0.

I added a fix so that the array test makes an exception for Ref. I previously had an exception for Fn::GetAtt and Fn::Split, but forgot Ref. Longer term I plan to add validation so I can check whether the attribute or parameter type (such as List<AWS::EC2::AvailabilityZone::Name>) resolves to an array.

My test case template looks like this: 

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Parameters": {
    "FooAvailabilityZones": {
      "Type": "List<AWS::EC2::AvailabilityZone::Name>",
      "Description":
        "List of AZ to deploy station in, example: 'eu-west-1a,eu-west-1b' "
    }
  },
  "Resources": {
    "ScalingGroupFoo": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        "AvailabilityZones": {
          "Ref": "FooAvailabilityZones"
        },
        "MaxSize": 1,
        "MinSize": 1
      }
    }
  }
}
```

i was able to reproduce the error, and my code change makes the error go away and allows the import to go through. Please let me know if this resolves the issue.

**Comment by paalvibe** [comment]
Thanks Armin,

This is really great. BTW your library looks really solid. I did a fix
myself in my local installation in the generate js, but a fix from you is
much better. Are
you able to update the npm module also?

Best regards,

Pål

**Comment by arminhammer** [comment]
Hi @paalvibe,

Thanks, I hope the library will end up being a useful tool for you. Feel free to continue opening up issues for features you need or bugs you run into. PRs are always welcome as well!

I updated the npm module when I created the fix. Go ahead and try installing 0.9.16 and let me know if it works.

**Comment by paalvibe** [comment]
It works. Amazing job!

Thanks a lot.
